version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2.6


jobs:
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run test
          command: npm test

workflows:
  build-and-heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
